spring:
  config:
    activate:
      on-profile: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher     # swagger 2.6.x부터 pathmatch가 변경되어 ' ant_path_matcher'를 주입
  jpa:
    show-sql: true # true 설정시 JPA 쿼리문 확인 가능
    hibernate:
      ddl-auto: none # DDL(create, alter, drop) 정의시 DB의 고유 기능을 사용할 수 있다.
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
    open-in-view: false
  redis:
    host: www.nogari.me
    port: 6379
    password: regari
  session:
    store-type: redis
  main:
    lazy-initialization: true

springdoc:
  packages-to-scan: me.nogari.nogari # swagger를 적용하기 위해 스캔할 패키지를 지정합니다.
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html            # Swagger UI 경로 => localhost:8080/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  cache:
    disabled: true

server:
  port: 8080              # 서비스 포트지정
  servlet:
    context-path: /api/v1     # contextPaht를 지정하면 기본 uri가 지정된다.

app:
  auth:
    tistory:
      redirect-uri: https://www.nogari.me/oauth/tistory    # Token 받을 Uri 지정
#      redirect-uri: http://localhost:3000/oauth/tistory     # Token 받을 Uri 지정
    notion:
      redirect-uri: https://www.nogari.me/oauth/notion    # notion access token 발급 요청 uri

logging:
  level:
    web: INFO
    com: INFO
    root: INFO
